sources_inclusion_list:
  - name: uniprot
    location: gs://open-targets-pre-data-releases/24.06/input/evidence-files/uniprot.json.gz ## input
    format: json
  - name: clinvar
    location: gs://open-targets-pre-data-releases/24.06/input/evidence-files/eva.json.gz
    format: json
  - name: pharmgkb
    location: gs://open-targets-pre-data-releases/24.06/input/pharmacogenomics-inputs/pharmacogenomics.json.gz
    format: json
  - name: gentropy_credible_sets
    location: gs://genetics_etl_python_playground/releases/24.06/credible_set
    format: parquet
